### ISSUE TITLE
Cannot resolve dependency

### ISSUE THREAD

**Issue by webloper** [GuillaumeBiton/framework7-parcel-template#2]
I used kitchen-sink code from framework7 and getting this error, can't find the reason to solve the issue, copied pages to dist folder also, but nothing changes.

`<!-- Link to another page -->`
`<a href="/about/">About app</a>`

>  E:\projects\parcel\my-app\index.html: Cannot resolve dependency './..\..\..\about'
 at 'E:\about'

**Comment by GuillaumeBiton** [comment]
There are some issues for the moment with parcel when you are using virtual router like Framework7's one.
